name: Create Release Tag
description: Creates a release tag for the given packageID
inputs:
  packageID:
    description: PackageID of the package.json
    required: true
    default: "test.package"
outputs:
  version:
    description: The version of the package.json
    value: ${{ steps.version.outputs.prop }}
  tag:
    description: The generated release tag of the package.json
    value: ${{ steps.tag.outputs.prop }}
runs:
  using: 'composite'
  steps:
    - name: get version
      id: version
      uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
      with: 
          path: "Packages/${{inputs.packageID}}/package.json"
          prop_path: "version"
    
    - name: get name
      id: name
      uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
      with: 
          path: "Packages/${{inputs.packageID}}/package.json"
          prop_path: "displayName"
    
    - name: sanitize name
      id: sanitizeName
      run: echo prop=$(echo '${{ steps.name.outputs.prop }}' | tr ' ' '_') >> $GITHUB_OUTPUT
    
    - name: generate tag
      id: tag
      run: echo prop="${{ steps.sanitizeName.outputs.prop }}-${{ steps.version.outputs.prop }}" >> $GITHUB_OUTPUT