name: Build Release

on: 
  workflow_dispatch:

env:
  releaseTemplate: "RELEASE TEMPLATE.md"
  packages: ["com.happyrobot33.packagewindowconsolidator", "com.happyrobot33.placeholder"]

permissions:
  contents: write

jobs:
  #this job checks every package to see if that package should have a release candidate
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packageID: ${{ env.packages }}
    outputs:
      ${{ matrix.packageID }}: ${{ steps.tagExists.outputs.exists }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Release Tag
        id: createReleaseTag
        uses: ./.github/workflows/create-release-tag/action.yml
        with:
          packageID: ${{ matrix.packageID }}
      
      - name: Check if Release Tag Exists
        uses: mukunku/tag-exists-action@v1.2.0
        id: tagExists
        with:
          tag: ${{ steps.createReleaseTag.outputs.tag }}
      
  #this job combines all of the checked packages into a single list of packageIDs that should have a release candidate made
  combine:
    needs: check
    runs-on: ubuntu-latest
    outputs:
      packageIDList: ${{ steps.combine.outputs.packages }}
    steps:
      - name: Combine Packages
        id: combine
        run: |
          packages=""
          for packageID in ${{ env.packages }}
          do
            if [ ${{ needs.check.outputs.${{ packageID }} }} == "true" ]
            then
              packages="$packages $packageID"
            fi
          done
          echo "packages=$packages" >> $GITHUB_ENV

  #this job builds every packageID it is given
  build:
    needs: combine
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packageID: ${{ fromJson(needs.combine.outputs.packageIDList) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Create Release Tag
        id: createReleaseTag
        uses: ./.github/workflows/create-release-tag/action.yml
        with:
          packageID: ${{ matrix.packageID }}

      - name: Set Environment Variables
        run: |
          echo "zipFile=${{ matrix.packageID }}-${{ steps.createReleaseTag.outputs.version }}".zip >> $GITHUB_ENV
          echo "unityPackage=${{ matrix.packageID }}-${{ steps.createReleaseTag.outputs.version }}.unitypackage" >> $GITHUB_ENV
        
      - name: Create Zip
        uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: "Packages/${{matrix.packageID}}/"
          filename: "../../${{env.zipFile}}" # make the zip file two directories up, since we start two directories in above
          
      - run: find "Packages/${{matrix.packageID}}/" -name \*.meta >> metaList
          
      - name: Create UnityPackage
        uses: pCYSl5EDgo/create-unitypackage@cfcd3cf0391a5ef1306342794866a9897c32af0b
        with:
          package-path: ${{ env.unityPackage }}
          include-files: metaList
        
      - name: Read Release Template
        id: ReleaseTemplateContents
        uses: juliangruber/read-file-action@v1.1.6
        with:
          path: "./${{ env.releaseTemplate }}"
        
      - name: Make Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        with:
          tag_name: ${{ steps.createReleaseTag.outputs.tag }}
          files: |
            ${{ env.zipFile }}
            ${{ env.unityPackage }}
            Packages/${{ matrix.packageID }}/package.json
          body: |
            ${{ steps.ReleaseTemplateContents.outputs.content }}
          prerelease: true
