name: Build Release

on: 
  workflow_dispatch:

env:
  releaseTemplate: "RELEASE TEMPLATE.md"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packageID: [com.happyrobot33.packagewindowconsolidator, test.example.package]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with: 
            path: "Packages/${{matrix.packageID}}/package.json"
            prop_path: "version"
      
      - name: get name
        id: name
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with: 
            path: "Packages/${{matrix.packageID}}/package.json"
            prop_path: "displayName"
      
      - name: sanitize name
        id: sanitizeName
        run: echo prop=$(echo '${{ steps.name.outputs.prop }}' | tr ' ' '_') >> $GITHUB_OUTPUT
    
      - name: Set Environment Variables
        run: |
          echo "zipFile=${{ matrix.packageID }}-${{ steps.version.outputs.prop }}".zip >> $GITHUB_ENV
          echo "unityPackage=${{ matrix.packageID }}-${{ steps.version.outputs.prop }}.unitypackage" >> $GITHUB_ENV
        
      - name: Create Zip
        uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: "Packages/${{matrix.packageID}}/"
          filename: "../../${{env.zipFile}}" # make the zip file two directories up, since we start two directories in above
          
      - run: find "Packages/${{matrix.packageID}}/" -name \*.meta >> metaList
          
      - name: Create UnityPackage
        uses: pCYSl5EDgo/create-unitypackage@cfcd3cf0391a5ef1306342794866a9897c32af0b
        with:
          package-path: ${{ env.unityPackage }}
          include-files: metaList
        
      - name: Read Release Template
        id: ReleaseTemplateContents
        uses: juliangruber/read-file-action@v1.1.6
        with:
          path: "./${{ env.releaseTemplate }}"
        
      - name: Make Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        with:
          tag_name: "${{ steps.sanitizeName.outputs.prop }}-${{ steps.version.outputs.prop }}"
          files: |
            ${{ env.zipFile }}
            ${{ env.unityPackage }}
            Packages/${{ matrix.packageID }}/package.json
          body: |
            ${{ steps.ReleaseTemplateContents.outputs.content }}
          prerelease: true
